# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@5.0.0

executors:
  go:
    docker:
      - image: cimg/go:1.18.0

jobs:
  build-singlepackage:
    executor: win/default
    steps:
      - checkout
      - run:
          command: |
            export VERSION=${CIRCLE_TAG:=$(git tag | tail -n1 | sed -rn 's/([0-9]+)\.([0-9]+).*/\1.\2/p').$(date '+%m%d').$(date '+%H%M')}
            mkdir releases
            echo $VERSION > releases/version.txt
            dotnet publish -c Release -o ./releases --no-self-contained -p:PublishSingleFile=true -p:AssemblyVersion=${VERSION:=0.0.1}
          shell: bash.exe
      - persist_to_workspace:
          root: .
          paths:
            - ./releases
  upload-github:
    executor: go
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: |
          go install github.com/tcnksm/ghr@latest
          export VERSION=$(cat artifacts/releases/version.txt)
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/releases/*.exe
      - store_artifacts:
          path: ./artifacts/releases

workflows:
  build-and-push:
    jobs:
      - build-singlepackage
      - upload-github:
          requires:
            - build-singlepackage